import { FormControl, FormGroup } from "@angular/forms";

export function eclaimsForm() {
  return new FormGroup({
    patient_id: new FormControl<string|null>(null),
    facility_code: new FormControl<string|null>(null),
    program_desc: new FormControl<string|null>(null),
    program_id: new FormControl<string|null>(null),
    admit_dx: new FormControl<string|null>(null),
    caserate_date: new FormControl<string|null>(null),
    caserate_code: new FormControl<string|null>(null),
    code: new FormControl<string|null>(null),
    description: new FormControl<string|null>(null),
    discharge_dx: new FormControl<string|null>(null),
    icd10_code: new FormControl<string|null>(null),
    hci_fee: new FormControl<string|null>(null),
    prof_fee: new FormControl<string|null>(null),
    caserate_fee: new FormControl<string|null>(null),
    admission_date: new FormControl<string|null>(null),
    admission_time: new FormControl<string|null>(null),
    discharge_date: new FormControl<string|null>(null),
    discharge_time: new FormControl<string|null>(null),
    eclaims_caserate_list_id: new FormControl<string|null>(null),
    attendant_accreditation_code: new FormControl<string|null>(null),
    attendant_last_name: new FormControl<string|null>(null),
    attendant_first_name: new FormControl<string|null>(null),
    attendant_middle_name: new FormControl<string|null>(null),
    attendant_suffix_name: new FormControl<string|null>(null),
    attendant_sign_date: new FormControl<string|null>(null),
    pTBType: new FormControl<string|null>(null),
    pNTPCardNo: new FormControl<string|null>(null),
    pDay0ARV: new FormControl<string|null>(null),
    pDay3ARV: new FormControl<string|null>(null),
    pDay7ARV: new FormControl<string|null>(null),
    pRIG: new FormControl<string|null>(null),
    pABPOthers: new FormControl<string|null>(null),
    pABPSpecify: new FormControl<string|null>(null),
    pEssentialNewbornCare: new FormControl<string|null>(null),
    pNewbornHearingScreeningTest: new FormControl<string|null>(null),
    pNewbornScreeningTest: new FormControl<string|null>(null),
    pFilterCardNo: new FormControl<string|null>(null),
    pCheckUpDate1: new FormControl<string|null>(null),
    pCheckUpDate2: new FormControl<string|null>(null),
    pCheckUpDate3: new FormControl<string|null>(null),
    pCheckUpDate4: new FormControl<string|null>(null),
    pICDCode: new FormControl<string|null>(null),
    transmittalNumber: new FormControl<string|null>(null),

    enough_benefit_flag: new FormControl<string|null>(null),
    hci_pTotalActualCharges: new FormControl<string|null>(null),
    hci_pDiscount: new FormControl<string|null>(null),
    hci_pPhilhealthBenefit: new FormControl<string|null>(null),
    hci_pTotalAmount: new FormControl<string|null>(null),
    prof_pTotalActualCharges: new FormControl<string|null>(null),
    prof_pDiscount: new FormControl<string|null>(null),
    prof_pPhilhealthBenefit: new FormControl<string|null>(null),
    prof_pTotalAmount: new FormControl<string|null>(null),
    meds_flag: new FormControl<string|null>(null),
    meds_pDMSTotalAmount: new FormControl<string|null>(null),
    meds_pExaminations_flag: new FormControl<string|null>(null),
    meds_pExamTotalAmount: new FormControl<string|null>(null),
    hmo_flag: new FormControl<string|null>(null),
    others_flag: new FormControl<string|null>(null)
  });
}
