import { FormControl, FormGroup } from "@angular/forms";

export function intakeForm() {
  return new FormGroup({
    id: new FormControl<string| null>(''),
    patient_id: new FormControl<string| null>(''),
    patient_gbv_id: new FormControl<string| null>(''),
    case_number: new FormControl<string| null>(''),
    case_date: new FormControl<string| null>(''),
    primary_complaint_id: new FormControl<string| null>(''),
    primary_complaint_remarks: new FormControl<string| null>(''),
    physical_abuse_flag: new FormControl<boolean| null>(false),
    sexual_abuse_flag: new FormControl<boolean| null>(false),
    neglect_abuse_flag: new FormControl<boolean| null>(false),
    emotional_abuse_flag: new FormControl<boolean| null>(false),
    economic_abuse_flag: new FormControl<boolean| null>(false),
    utv_abuse_flag: new FormControl<boolean| null>(false),
    others_abuse_flag: new FormControl<boolean| null>(false),
    others_abuse_remarks: new FormControl<string| null>(''),
    neglect_remarks: new FormControl<string| null>(''),
    behavioral_remarks : new FormControl<string| null>(''),
    service_id : new FormControl<string| null>(''),
    service_remarks : new FormControl<string| null>(''),
    region : new FormControl<string| null>(''),
    province : new FormControl<string| null>(''),
    municipality : new FormControl<string| null>(''),
    same_address_flag: new FormControl<boolean| null>(false),
    barangay_code : new FormControl<string| null>(''),
    address : new FormControl<string| null>(''),
    direction_to_address : new FormControl<string| null>(''),
    guardian_name : new FormControl<string| null>(''),
    guardian_address : new FormControl<string| null>(''),
    relation_to_child_id : new FormControl<string| null>(''),
    guardian_contact_info : new FormControl<string| null>(''),
    economic_status_id : new FormControl<string| null>(''),
    number_of_children : new FormControl<string| null>(''),
    number_of_individual_members : new FormControl<string| null>(''),
    number_of_family : new FormControl<string| null>(''),
    incest_case_flag : new FormControl<boolean| null>(false),
    sleeping_arrangement_id : new FormControl<string| null>(''),
    sleeping_arrangement_remarks : new FormControl<string| null>(''),
    same_bed_adult_male_flag : new FormControl<boolean| null>(false),
    same_bed_adult_female_flag : new FormControl<boolean| null>(false),
    same_bed_child_male_flag : new FormControl<boolean| null>(false),
    same_bed_child_female_flag : new FormControl<boolean| null>(false),
    same_room_adult_male_flag : new FormControl<boolean| null>(false),
    same_room_adult_female_flag : new FormControl<boolean| null>(false),
    same_room_child_male_flag : new FormControl<boolean| null>(false),
    same_room_child_female_flag : new FormControl<boolean| null>(false),
    abuse_living_arrangement_id : new FormControl<string| null>(''),
    abuse_living_arrangement_remarks : new FormControl<string| null>(''),
    present_living_arrangement_id : new FormControl<string| null>(''),
    present_living_arrangement_remarks : new FormControl<string| null>(''),

    vaw_physical_flag : new FormControl<boolean| null>(false),
    vaw_sexual_flag : new FormControl<boolean| null>(false),
    vaw_psychological_flag : new FormControl<boolean| null>(false),
    vaw_economic_flag : new FormControl<boolean| null>(false),
    rape_sex_intercourse_flag : new FormControl<boolean| null>(false),
    rape_sex_assault_flag : new FormControl<boolean| null>(false),
    rape_incest_flag : new FormControl<boolean| null>(false),
    rape_statutory_flag : new FormControl<boolean| null>(false),
    rape_marital_flag : new FormControl<boolean| null>(false),
    harassment_verbal_flag : new FormControl<boolean| null>(false),
    harassment_physical_flag : new FormControl<boolean| null>(false),
    harassment_object_flag : new FormControl<boolean| null>(false),
    child_abuse_engaged_flag : new FormControl<boolean| null>(false),
    child_abuse_sexual_flag : new FormControl<boolean| null>(false),
    child_abuse_physical_flag : new FormControl<boolean| null>(false),
    child_abuse_emotional_flag : new FormControl<boolean| null>(false),
    child_abuse_economic_flag : new FormControl<boolean| null>(false),
    wcpd_others : new FormControl<string| null>(''),
  });
}
