import { FormControl, FormGroup } from "@angular/forms";

export function interviewForm() {
  return new FormGroup({
    id: new FormControl<string| null>(''),
    patient_id: new FormControl<string| null>(''),
    patient_gbv_intake_id: new FormControl<string| null>(''),
    recant_flag: new FormControl<string| null>(''),
    recant_datetime: new FormControl<string| null>(''),
    recant_remarks: new FormControl<string| null>(''),
    interview_datetime: new FormControl<string| null>(''),
    deferred: new FormControl<boolean| null>(false),
    deferral_datetime: new FormControl<boolean| null>(false),
    deferral_reason_id : new FormControl<number| null>(null),
    deferral_previous_interviewer_id : new FormControl<number| null>(null),
    deferral_interviewer_remarks: new FormControl<string| null>(''),

    source_from_victim_flag: new FormControl<boolean| null>(false),
    source_from_historian_flag: new FormControl<boolean| null>(false),
    source_from_historian_remarks: new FormControl<string| null>(null),
    source_from_sworn_statement_flag: new FormControl<boolean| null>(false),
    mental_age_id: new FormControl<string| null>(''),

    incident_first_unknown: new FormControl<string| null>(''),
    incident_first_datetime: new FormControl<string| null>(''),
    incident_first_remarks : new FormControl<string| null>(''),
    incident_recent_unknown: new FormControl<string| null>(''),
    incident_recent_datetime : new FormControl<string| null>(''),
    incident_recent_remarks: new FormControl<string| null>(''),

    abused_episode_id  : new FormControl<string| null>(''),
    abused_episode_count  : new FormControl<number| null>(null),
    abused_site_id : new FormControl<string| null>(''),
    abused_site_remarks : new FormControl<string| null>(''),
    disclosed_flag : new FormControl<boolean| null>(false),
    disclosed_type : new FormControl<string| null>(''),
    disclosed_relation_id : new FormControl<string| null>(''),
    initial_disclosure : new FormControl<string| null>(''),

    relation_to_child : new FormControl<string| null>(''),

    behavior_cooperative_flag : new FormControl<boolean| null>(false),
    behavior_crying_flag : new FormControl<boolean| null>(false),
    behavior_clinging_flag : new FormControl<boolean| null>(false),
    behavior_responsive_flag : new FormControl<boolean| null>(false),
    behavior_silent_flag : new FormControl<boolean| null>(false),
    behavior_able_to_narrate_flag : new FormControl<boolean| null>(false),
    behavior_unable_to_narrate_flag : new FormControl<boolean| null>(false),
    behavior_appropriate_affect_flag : new FormControl<boolean| null>(false),
    behavior_depressed_affect_flag : new FormControl<boolean| null>(false),
    behavior_flat_affect_flag : new FormControl<boolean| null>(false),
    behavior_psychotic_flag : new FormControl<boolean| null>(false),
    behavior_combative_flag : new FormControl<boolean| null>(false),
    behavior_hyperactive_flag : new FormControl<boolean| null>(false),
    behavior_short_attention_flag : new FormControl<boolean| null>(false),

    behavior_historian_cooperative_flag : new FormControl<boolean| null>(false),
    behavior_historian_crying_flag : new FormControl<boolean| null>(false),
    behavior_historian_clinging_flag : new FormControl<boolean| null>(false),
    behavior_historian_responsive_flag : new FormControl<boolean| null>(false),
    behavior_historian_silent_flag : new FormControl<boolean| null>(false),
    behavior_historian_able_to_narrate_flag : new FormControl<boolean| null>(false),
    behavior_historian_unable_to_narrate_flag : new FormControl<boolean| null>(false),
    behavior_historian_appropriate_affect_flag : new FormControl<boolean| null>(false),
    behavior_historian_depressed_affect_flag : new FormControl<boolean| null>(false),
    behavior_historian_flat_affect_flag : new FormControl<boolean| null>(false),
    behavior_historian_psychotic_flag : new FormControl<boolean| null>(false),
    behavior_historian_combative_flag : new FormControl<boolean| null>(false),
    behavior_historian_hyperactive_flag : new FormControl<boolean| null>(false),
    behavior_historian_short_attention_flag : new FormControl<boolean| null>(false),
    behavior_historian_remarks : new FormControl<string| null>(''),

    child_caretaker_present_flag : new FormControl<boolean| null>(false),
    child_behavior_remarks : new FormControl<string| null>(''),
    dev_screening_id : new FormControl<string| null>(''),
    dev_screening_remarks : new FormControl<string| null>(''),
  });
}
