import { FormControl, FormGroup } from "@angular/forms";

export const riskAssessForm: FormGroup = new FormGroup({
  consult_id: new FormControl<string| null>(null),
  patient_id: new FormControl<string| null>(null),
  location: new FormControl<string| null>(null),
  client_type: new FormControl<string| null>(null),
  assessment_date: new FormControl<string| null>(null),
  family_hx_hypertension: new FormControl<string| null>(null),
  family_hx_stroke: new FormControl<string| null>(null),
  family_hx_heart_attack: new FormControl<string| null>(null),
  family_hx_diabetes: new FormControl<string| null>(null),
  family_hx_asthma: new FormControl<string| null>(null),
  family_hx_cancer: new FormControl<string| null>(null),
  family_hx_kidney_disease: new FormControl<string| null>(null),
  smoking: new FormControl<string| null>(null),
  alcohol_intake: new FormControl<string| null>(null),
  excessive_alcohol_intake: new FormControl<string| null>(null),
  high_fat: new FormControl<string| null>(null),
  intake_vegetables: new FormControl<string| null>(null),
  intake_fruits: new FormControl<string| null>(null),
  physical_activity: new FormControl<string| null>(null),
  presence_diabetes: new FormControl<string| null>(null),
  diabetes_medications: new FormControl<string| null>(null),
  polyphagia: new FormControl<string| null>(null),
  polydipsia: new FormControl<string| null>(null),
  polyuria: new FormControl<string| null>(null),
  obesity: new FormControl<string| null>(null),
  central_adiposity: new FormControl<string| null>(null),
  bmi: new FormControl<string| null>(null),
  waist_line: new FormControl<string| null>(null),
  raised_bp: new FormControl<string| null>(null),
  avg_systolic: new FormControl<string| null>(null),
  avg_diastolic: new FormControl<string| null>(null),
  systolic_1st: new FormControl<string| null>(null),
  diastolic_1st: new FormControl<string| null>(null),
  systolic_2nd: new FormControl<string| null>(null),
  diastolic_2nd: new FormControl<string| null>(null)
});
