import { FormControl, FormGroup } from "@angular/forms";

export const riskAssessForm: FormGroup = new FormGroup({
  patient_ncd_id: new FormControl<string| null>(''),
  patient_id: new FormControl<string| null>(''),
  location: new FormControl<string| null>(''),
  client_type: new FormControl<string| null>(''),
  assessment_date: new FormControl<string| null>(''),
  family_hx_hypertension: new FormControl<string| null>(''),
  family_hx_stroke: new FormControl<string| null>(''),
  family_hx_heart_attack: new FormControl<string| null>(''),
  family_hx_diabetes: new FormControl<string| null>(''),
  family_hx_asthma: new FormControl<string| null>(''),
  family_hx_cancer: new FormControl<string| null>(''),
  family_hx_kidney_disease: new FormControl<string| null>(''),
  smoking: new FormControl<string| null>(''),
  alcohol_intake: new FormControl<string| null>(''),
  excessive_alcohol_intake: new FormControl<string| null>(''),
  high_fat: new FormControl<string| null>(''),
  intake_vegetables: new FormControl<string| null>(''),
  intake_fruits: new FormControl<string| null>(''),
  physical_activity: new FormControl<string| null>(''),
  presence_diabetes: new FormControl<string| null>(''),
  diabetes_medication: new FormControl<string| null>(''),
  polyphagia: new FormControl<string| null>(''),
  polydipsia: new FormControl<string| null>(''),
  polyuria: new FormControl<string| null>(''),
  obesity: new FormControl<string| null>(''),
  central_adiposity: new FormControl<string| null>(''),
  bmi: new FormControl<string| null>(''),
  waist_line: new FormControl<string| null>(''),
  raised_bp: new FormControl<string| null>(''),
  avg_systolic: new FormControl<string| null>(''),
  avg_diastolic: new FormControl<string| null>(''),
  systolic_1st: new FormControl<string| null>(''),
  diastolic_1st: new FormControl<string| null>(''),
  systolic_2nd: new FormControl<string| null>(''),
  diastolic_2nd: new FormControl<string| null>(''),
  gender: new FormControl<string| null>(''),
  age: new FormControl<string| null>('')
});
